name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        doctrine-orm-version: ["2.0", "3.0"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Set Doctrine Version
        run: |
          composer require doctrine/orm:"^${{ matrix.doctrine-orm-version }}" -W

      - name: Coding standards
        run: make check

      - name: Static Analysis
        run: make analyze_ci

      - name: Run tests
        run: make tests
